services:
  almalinux-9:
    build:
      context: .
      dockerfile: dockerfiles/almalinux.dockerfile
      args:
        VERSION: "9"
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  almalinux-10:
    build:
      context: .
      dockerfile: dockerfiles/almalinux.dockerfile
      args:
        VERSION: "10"
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  alpine-linux:
    build:
      context: .
      dockerfile: dockerfiles/alpine-linux.dockerfile
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  arch-linux:
    build:
      context: .
      dockerfile: dockerfiles/arch-linux.dockerfile
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  conda:
    build:
      context: .
      dockerfile: dockerfiles/conda.dockerfile
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  debian-11:
    build:
      context: .
      dockerfile: dockerfiles/debian.dockerfile
      args:
        VERSION: "11"
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  debian-12:
    build:
      context: .
      dockerfile: dockerfiles/debian.dockerfile
      args:
        VERSION: "12"
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  fedora-rawhide:
    build:
      context: .
      dockerfile: dockerfiles/fedora.dockerfile
      args:
        FEDORA_VERSION: rawhide
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  ruby-3.2:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        RUBY_VERSION: "3.2"
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  ruby-3.3:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        RUBY_VERSION: "3.3"
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  ruby-3.4:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        RUBY_VERSION: "3.4"
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  ubuntu-22.04:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu.dockerfile
      args:
        UBUNTU_VERSION: "22.04"
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh

  ubuntu-24.04:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu.dockerfile
      args:
        UBUNTU_VERSION: "24.04"
    volumes:
      - .:/rcairo:delegated
    command:
      /rcairo/dockerfiles/run-test.sh
