#!/usr/bin/env ruby
# vim: set ts=2 sw=2 et :

$LOAD_PATH << "../src"
require 'cairo'

class SplineWindow < Cairo::Xlib::Window
  def initialize(dpy)
    @width = @height = 400
    super(dpy, @width, @height, false)
  end

  def randx
    10 + rand(@width-20)
  end
  def randy
    10 + rand(@height-20)
  end

  def draw
    @cairo.set_rgb_color(1, 1, 1)
    @cairo.line_cap = Cairo::LineCap::ROUND
    @cairo.line_width = 2 + ((rand**2.0) * 50)
    @cairo.stroke {
      @cairo.move_to(randx, randy)
      @cairo.curve_to(randx, randy, randx, randy, randx, randy)
    }
  end

  def keypress(key)
    case key.chr
    when 'q'
      @dpy.quit
    end
  end
end

dpy = Cairo::Xlib::Display.new
sw = SplineWindow.new(dpy)
puts "Tap keys to get new splines..."
dpy.mainloop


