#!/usr/bin/env ruby
# vim: set ts=2 sw=2 et :

require 'cairo'

puts <<EOT
A diagonal line, from top-left to bottom-right, looks like this:

EOT

img = Cairo::Image.new(0, 8, 8, 8*4)

cairo = Cairo::Cairo.new
cairo.target_image = img

# cairo.set_rgb_color(0, 0, 0)
# cairo.fill {
#   cairo.move_to(0, 0)
#   cairo.line_to(8, 0)
#   cairo.line_to(8, 8)
#   cairo.line_to(0, 8)
#   cairo.close_path
# }

cairo.set_rgb_color(1, 1, 1)
cairo.stroke {
  cairo.move_to(0, 0)
  cairo.line_to(8, 8)
}

lasty = 0
img.each_pixel { |x, y, p|
  (puts; puts) if y != lasty
  print ("%08x" % p) + " "
  lasty = y
}
puts; puts

