#!/usr/bin/env ruby

require 'mkmf'
$CFLAGS << " -g -Wall `pkg-config --cflags cairo`"
$LDFLAGS << " `pkg-config --libs cairo`"

# remove autogenerated files
$distcleanfiles << 'gen-*.c'

create_makefile("cairo")
