name: macOS
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Install
        run: |
          # Need to install cairo gem as a normal gem to find rb_cairo.h by
          # other gems cairo-gobject gem and so on.
          gem build cairo.gemspec
          gem install *.gem
          bundle install
      - name: Test
        run: |
          bundle exec rake
