name: Release
on:
  - push
  - pull_request
jobs:
  github:
    name: GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          ruby \
            -e 'print("## "); puts(ARGF.read.split(/^## /)[1])' \
            NEWS.md | tee release-note.md
          title="$(head -n 1 release-note.md | sed -e 's/^## //')"
          echo "TITLE=${title}" >> "${GITHUB_ENV}"
          tail -n +2 release-note.md | tee release-note-without-version.md
      - name: Publish
        if: github.ref_type == 'tag'
        run: |
          gh release create \
            ${GITHUB_REF_NAME} \
            --discussion-category Announcements \
            --notes-file release-note-without-version.md \
            --title "${TITLE}"
        env:
          GH_TOKEN: ${{ github.token }}

  rubygems:
    name: RubyGems
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: ${{ github.ref_type == 'tag' && 'write' || 'read' }}
    environment: ${{ github.ref_type == 'tag' && 'release' || '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Disable test group
        run: |
          bundle config without test
      - name: Install dependencies
        run: |
          bundle install
      - name: Build
        if: github.ref_type != 'tag'
        run: |
          bundle exec rake build
      - uses: rubygems/configure-rubygems-credentials@v1.0.0
        if: github.ref_type == 'tag'
      - name: Push
        if: github.ref_type == 'tag'
        run: |
          bundle exec rake release:rubygem_push
