name: Windows
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.0"
          - "3.1"
          - "3.2"
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install
        run: |
          # Need to install cairo gem as a normal gem to find rb_cairo.h by
          # other gems cairo-gobject gem and so on.
          gem build cairo.gemspec
          gem install *.gem
          bundle install
      - name: Build
        run: |
          bundle exec ruby -rdevkit extconf.rb
          ridk exec make
      - name: Test
        run: |
          bundle exec ruby test/run-test.rb
